language: python

python:
  - "3.8"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

# https://docs.travis-ci.com/user/caching/#before_cache-phase
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

env:
  global:
    - OMP_NUM_THREADS=4
    - CUDA_VISIBLE_DEVICES=-1

before_install:
  - sudo apt-get install --yes graphviz
  - pip install --upgrade pip
  - pip install poetry
  - poetry config cache-dir "$HOME/.cache/pypoetry"

install:
  - poetry install --extras "tests tensorflow-cpu"
  - poetry run pip install "git+https://github.com/cocodataset/coco.git#egg=pycocotools&subdirectory=PythonAPI"

script:
  - make test
