[tool.poetry]
name = "pytoolkit"
version = "0.1.0"
description = "pytoolkit: Personal Python package"
license = "MIT"
authors = ["aki. <mark@aur.ll.to>"]
readme = "README.md"
homepage = "https://github.com/ak110/pytoolkit"
repository = "https://github.com/ak110/pytoolkit.git"
documentation = "https://ak110-pytoolkit.readthedocs.io/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
albumentations = "^0.4.5"
numba = "^0.49.1"
pandas = "^1.0.3"
scikit-learn = "^0.23.0"
better-exceptions = {version = "^0.2.2", optional = true}
catboost = {version = "^0.23.1", optional = true}
category_encoders = {version = "^2.2.2", optional = true}
chainercv = {version = "^0.13.1", optional = true}
h5py = {version = "^2.10.0", optional = true}
horovod = {version = "^0.19.2", optional = true}
ipython = {version = "^7.14.0", optional = true}
keras2onnx = {version = "^1.6.1", optional = true}
lightgbm = {version = "^2.3.1", optional = true}
matplotlib = {version = "^3.2.1", optional = true}
mpi4py = {version = "^3.0.3", optional = true}
onnxmltools = {version = "^1.6.1", optional = true}
optuna = {version = "^1.4.0", optional = true}
python-dotenv = {version = "^0.13.0", optional = true}
requests = {version = "^2.23.0", optional = true}
tensorflow = {version = "^2.2.0", optional = true}
tf2onnx = {version = "^1.5.6", optional = true}
tqdm = {version = "^4.46.0", optional = true}
xgboost = {version = "^1.0.2", optional = true}

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
mypy = "^0.770"
pylint = "^2.4.4"
pytest = "^5.3.5"

[tool.poetry.scripts]
tk-benchmark = "pytoolkit.bin.benchmark:main"
tk-convert-model = "pytoolkit.bin.convertmodel:main"
tk-plot-log = "pytoolkit.bin.plotlog:main"
tk-py2nb = "pytoolkit.bin.py2nb:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
